2017-01-30 01:33:40,084 - temperature_sensor._run - ERROR - Error in tmperature sensor
Traceback (most recent call last):
  File "D:\pi3diamondnew\hardware\temperature_sensor.py", line 91, in _run
    temperature = float(buffer[40:45])
ValueError: invalid literal for float(): 2idit
2017-01-30 14:16:59,854 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x2FB3A360>, trait: slider, old value: -4.4, new value: -4.098
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 373, in call_2
    self.handler( object, new )
  File "D:\pi3diamondnew\measurements\confocal.py", line 554, in _slider_changed
    self.ao.Write(np.array((new), dtype=np.float64) )
NameError: global name 'np' is not defined
2017-01-30 14:17:00,164 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x2FB3A360>, trait: slider, old value: -4.098, new value: 3.77
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 373, in call_2
    self.handler( object, new )
  File "D:\pi3diamondnew\measurements\confocal.py", line 554, in _slider_changed
    self.ao.Write(np.array((new), dtype=np.float64) )
NameError: global name 'np' is not defined
2017-01-30 14:17:08,194 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x2FB3A360>, trait: slider, old value: 3.77, new value: 3.77
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 373, in call_2
    self.handler( object, new )
  File "D:\pi3diamondnew\measurements\confocal.py", line 554, in _slider_changed
    self.ao.Write(np.array((new), dtype=np.float64) )
NameError: global name 'np' is not defined
2017-01-30 14:19:13,335 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x17DB8E70>, trait: slider, old value: -4.4, new value: -2.402
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 373, in call_2
    self.handler( object, new )
  File "D:\pi3diamondnew\measurements\confocal.py", line 554, in _slider_changed
    self.ao.Write(numpy.array((new), dtype=np.float64) )
NameError: global name 'np' is not defined
2017-01-30 17:44:03,019 - pi3diamond.<module> - INFO - Starting logger.
2017-01-30 17:44:12,782 - emod.start - INFO - Starting Job Manager.
2017-01-30 17:44:12,812 - cron.run - INFO - Starting Cron Daemon.
2017-01-31 16:08:21,694 - auto_focus.focus - INFO - Focus: 25.00, 25.30, -2.52
2017-01-31 16:42:50,596 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x07295D80> is already running or in the queue.
2017-01-31 16:45:33,697 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x07295D80> is already running or in the queue.
2017-01-31 16:45:45,377 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x07295D80> is already running or in the queue.
2017-01-31 16:46:07,917 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x07295D80> is already running or in the queue.
2017-01-31 16:46:30,407 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x07295D80> is already running or in the queue.
2017-01-31 16:46:41,648 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x07295D80> is already running or in the queue.
2017-01-31 16:46:53,038 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x07295D80> is already running or in the queue.
2017-01-31 16:47:04,288 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x07295D80> is already running or in the queue.
2017-01-31 16:47:20,631 - pi3diamond.<module> - INFO - Starting logger.
2017-01-31 16:47:29,131 - emod.start - INFO - Starting Job Manager.
2017-01-31 16:47:29,180 - cron.run - INFO - Starting Cron Daemon.
2017-01-31 16:49:03,210 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x0721BC00> is already running or in the queue.
2017-01-31 16:49:14,500 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x0721BC00> is already running or in the queue.
2017-01-31 16:49:25,740 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x0721BC00> is already running or in the queue.
2017-01-31 16:52:20,062 - pi3diamond.<module> - INFO - Starting logger.
2017-01-31 16:52:22,711 - emod.start - INFO - Starting Job Manager.
2017-01-31 16:52:22,711 - cron.run - INFO - Starting Cron Daemon.
2017-01-31 16:53:51,221 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x0723CE10> is already running or in the queue.
2017-01-31 16:54:02,461 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x0723CE10> is already running or in the queue.
2017-01-31 16:54:13,711 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x0723CE10> is already running or in the queue.
2017-01-31 16:54:24,961 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x0723CE10> is already running or in the queue.
2017-01-31 16:54:36,221 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x0723CE10> is already running or in the queue.
2017-01-31 16:54:47,451 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x0723CE10> is already running or in the queue.
2017-01-31 16:54:58,691 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x0723CE10> is already running or in the queue.
2017-01-31 16:55:09,921 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x0723CE10> is already running or in the queue.
2017-01-31 16:55:21,151 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x0723CE10> is already running or in the queue.
2017-01-31 16:55:32,381 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x0723CE10> is already running or in the queue.
2017-01-31 16:57:23,211 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x0723CE10> is already running or in the queue.
2017-01-31 16:57:35,441 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x0723CE10> is already running or in the queue.
2017-01-31 16:57:47,671 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x0723CE10> is already running or in the queue.
2017-01-31 16:57:59,901 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x0723CE10> is already running or in the queue.
2017-01-31 16:58:12,142 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x0723CE10> is already running or in the queue.
2017-01-31 16:58:24,374 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x0723CE10> is already running or in the queue.
2017-01-31 16:58:36,614 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x0723CE10> is already running or in the queue.
2017-01-31 16:58:48,854 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x0723CE10> is already running or in the queue.
2017-01-31 16:59:01,094 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x0723CE10> is already running or in the queue.
2017-01-31 16:59:13,344 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x0723CE10> is already running or in the queue.
2017-01-31 17:00:34,944 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x0723CE10> is already running or in the queue.
2017-01-31 17:00:50,184 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x0723CE10> is already running or in the queue.
2017-01-31 17:01:05,414 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x0723CE10> is already running or in the queue.
2017-01-31 17:01:20,664 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x0723CE10> is already running or in the queue.
2017-01-31 17:01:35,894 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x0723CE10> is already running or in the queue.
2017-01-31 17:06:29,125 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x0723CE10> is already running or in the queue.
2017-01-31 17:06:44,355 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x0723CE10> is already running or in the queue.
2017-01-31 17:06:59,585 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x0723CE10> is already running or in the queue.
2017-01-31 17:07:14,815 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x0723CE10> is already running or in the queue.
2017-01-31 17:07:30,045 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x0723CE10> is already running or in the queue.
2017-02-01 14:33:47,894 - pi3diamond.<module> - INFO - Starting logger.
2017-02-01 14:33:58,384 - emod.start - INFO - Starting Job Manager.
2017-02-01 14:33:58,414 - cron.run - INFO - Starting Cron Daemon.
2017-02-01 14:35:01,855 - pi3diamond.<module> - INFO - Starting logger.
2017-02-01 14:35:04,164 - emod.start - INFO - Starting Job Manager.
2017-02-01 14:35:04,464 - cron.run - INFO - Starting Cron Daemon.
2017-02-01 14:49:54,450 - pi3diamond.<module> - INFO - Starting logger.
2017-02-01 14:49:57,081 - emod.start - INFO - Starting Job Manager.
2017-02-01 14:49:57,081 - cron.run - INFO - Starting Cron Daemon.
2017-02-01 14:50:51,391 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x0722D150>, trait: resolution, old value: 31, new value: 1
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 1.0 <= a floating point number <= 400.0, but a value of 1000.0 <type 'float'> was specified.
2017-02-01 15:07:27,596 - auto_focus.focus - INFO - Focus: 27.38, 5.46, -0.35
2017-02-01 15:07:32,654 - auto_focus.focus - INFO - Focus: 27.48, 5.46, -0.20
2017-02-01 15:08:17,483 - auto_focus.focus - INFO - Focus: 27.88, 5.26, -0.95
2017-02-01 15:08:22,743 - auto_focus.focus - INFO - Focus: 28.08, 5.36, -1.40
2017-02-01 15:08:31,733 - auto_focus.focus - INFO - Focus: 27.98, 5.46, -1.55
2017-02-01 15:08:36,983 - auto_focus.focus - INFO - Focus: 27.98, 5.56, -1.40
2017-02-01 15:08:42,043 - auto_focus.focus - INFO - Focus: 27.98, 5.46, -1.25
2017-02-01 15:10:17,065 - auto_focus.focus - INFO - Focus: 28.18, 4.96, -1.55
2017-02-01 15:10:22,164 - auto_focus.focus - INFO - Focus: 28.48, 4.46, -1.55
2017-02-01 15:10:32,275 - auto_focus.focus - INFO - Focus: 28.88, 3.96, -1.70
2017-02-01 15:10:37,174 - auto_focus.focus - INFO - Focus: 29.28, 3.46, -1.70
2017-02-01 15:10:42,194 - auto_focus.focus - INFO - Focus: 29.68, 3.36, -1.85
2017-02-01 15:10:52,335 - auto_focus.focus - INFO - Focus: 29.98, 2.86, -1.85
2017-02-01 15:11:05,484 - auto_focus.focus - INFO - Focus: 30.18, 2.96, -1.70
2017-02-01 15:11:10,494 - auto_focus.focus - INFO - Focus: 30.18, 2.96, -1.85
2017-02-01 15:13:00,585 - auto_focus.focus - INFO - Focus: 22.15, 46.31, -1.85
2017-02-01 15:13:05,904 - auto_focus.focus - INFO - Focus: 22.05, 46.41, -1.70
2017-02-01 15:13:11,015 - auto_focus.focus - INFO - Focus: 22.05, 46.41, -1.85
2017-02-01 15:15:45,335 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x0722D150>, trait: resolution, old value: 40, new value: 400
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 1.0 <= a floating point number <= 400.0, but a value of 0.8333333333333334 <type 'float'> was specified.
2017-02-01 15:19:27,895 - auto_focus.focus - INFO - Focus: 21.95, 46.31, -2.00
2017-02-01 15:19:36,375 - auto_focus.focus - INFO - Focus: 21.45, 46.51, -2.15
2017-02-01 15:19:41,335 - auto_focus.focus - INFO - Focus: 21.35, 46.51, -2.00
2017-02-01 15:19:52,086 - auto_focus.focus - INFO - Focus: 21.75, 46.41, -1.85
2017-02-01 15:37:10,680 - auto_focus.focus - INFO - Focus: 22.15, 45.91, -1.10
2017-02-01 15:41:58,763 - auto_focus.focus - INFO - Focus: 21.25, 45.91, -1.10
2017-02-01 15:42:05,854 - auto_focus.focus - INFO - Focus: 21.55, 46.51, -1.10
2017-02-01 15:42:11,084 - auto_focus.focus - INFO - Focus: 21.55, 46.81, -0.35
2017-02-01 15:42:16,253 - auto_focus.focus - INFO - Focus: 21.35, 47.01, -0.20
2017-02-01 15:42:21,124 - auto_focus.focus - INFO - Focus: 21.35, 47.01, -0.20
2017-02-01 15:42:26,483 - auto_focus.focus - INFO - Focus: 21.35, 47.01, -0.20
2017-02-01 16:55:12,516 - pi3diamond.<module> - INFO - Starting logger.
2017-02-01 16:55:22,187 - emod.start - INFO - Starting Job Manager.
2017-02-01 16:55:22,217 - cron.run - INFO - Starting Cron Daemon.
2017-02-01 17:38:39,335 - auto_focus.focus - INFO - Focus: 21.55, 45.91, -1.25
2017-02-01 17:38:45,496 - auto_focus.focus - INFO - Focus: 21.05, 46.31, -0.80
2017-02-01 17:38:53,105 - auto_focus.focus - INFO - Focus: 20.55, 46.41, -0.50
2017-02-01 17:38:58,075 - auto_focus.focus - INFO - Focus: 20.35, 46.71, -0.50
2017-02-01 17:39:07,286 - auto_focus.focus - INFO - Focus: 19.85, 46.41, 0.10
2017-02-01 17:39:13,176 - auto_focus.focus - INFO - Focus: 19.75, 46.81, 0.70
2017-02-01 17:39:18,095 - auto_focus.focus - INFO - Focus: 20.15, 46.31, 1.15
2017-02-01 17:39:23,276 - auto_focus.focus - INFO - Focus: 20.15, 46.31, 1.15
2017-02-01 18:06:24,461 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x0737ACF0>, trait: resolution, old value: 300, new value: 1
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 1000.0 <type 'float'> was specified.
2017-02-01 18:08:00,473 - auto_focus.focus - INFO - Focus: 20.25, 46.41, 1.30
2017-02-01 18:08:09,493 - auto_focus.focus - INFO - Focus: 20.25, 46.41, 1.30
2017-02-01 18:08:18,253 - auto_focus.focus - INFO - Focus: 20.25, 46.41, 1.30
2017-02-01 18:08:35,654 - auto_focus.focus - INFO - Focus: 20.05, 46.81, 0.85
2017-02-01 18:38:31,888 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x0737ACF0>, trait: seconds_per_point, old value: 0.0001, new value: 5e-05
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 645.1612903225806 <type 'float'> was specified.
2017-02-01 18:39:16,428 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x0737ACF0>, trait: resolution, old value: 31, new value: 41
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 487.80487804878044 <type 'float'> was specified.
2017-02-01 18:43:59,960 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x0737ACF0>, trait: resolution, old value: 41, new value: 2
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 10000.0 <type 'float'> was specified.
2017-02-01 18:44:00,289 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x0737ACF0>, trait: resolution, old value: 2, new value: 20
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 1000.0 <type 'float'> was specified.
2017-02-01 18:49:25,589 - auto_focus.focus - INFO - Focus: 19.55, 46.41, 1.60
2017-02-01 18:49:55,990 - auto_focus.focus - INFO - Focus: 19.45, 46.61, 2.20
2017-02-01 18:50:07,569 - auto_focus.focus - INFO - Focus: 19.45, 46.71, 2.35
2017-02-01 18:50:12,630 - auto_focus.focus - INFO - Focus: 19.45, 46.71, 2.20
2017-02-01 18:50:20,990 - auto_focus.focus - INFO - Focus: 19.45, 46.71, 2.20
2017-02-01 19:05:07,288 - auto_focus.focus - INFO - Focus: 18.95, 46.21, 1.45
2017-02-01 19:05:12,167 - auto_focus.focus - INFO - Focus: 18.45, 46.31, 0.85
2017-02-01 19:05:17,058 - auto_focus.focus - INFO - Focus: 18.25, 46.41, 0.10
2017-02-01 19:05:24,237 - auto_focus.focus - INFO - Focus: 18.35, 46.41, -0.65
2017-02-01 19:05:29,148 - auto_focus.focus - INFO - Focus: 18.35, 46.41, -0.80
2017-02-01 19:05:34,028 - auto_focus.focus - INFO - Focus: 18.35, 46.41, -0.65
2017-02-01 19:05:39,098 - auto_focus.focus - INFO - Focus: 18.35, 46.41, -0.65
2017-02-02 09:21:37,017 - auto_focus.focus - INFO - Focus: 18.65, 45.91, 0.10
2017-02-02 09:21:41,977 - auto_focus.focus - INFO - Focus: 18.35, 45.51, 0.85
2017-02-02 09:21:46,897 - auto_focus.focus - INFO - Focus: 18.45, 45.21, 1.30
2017-02-02 09:21:51,746 - auto_focus.focus - INFO - Focus: 18.85, 45.31, 1.90
2017-02-02 09:21:56,657 - auto_focus.focus - INFO - Focus: 18.85, 45.31, 1.75
2017-02-02 09:42:46,088 - auto_focus.focus - INFO - Focus: 18.35, 45.41, 2.05
2017-02-02 09:42:50,987 - auto_focus.focus - INFO - Focus: 18.45, 45.41, 2.05
2017-02-02 09:42:59,437 - auto_focus.focus - INFO - Focus: 18.35, 45.41, 1.90
2017-02-02 10:55:57,855 - pi3diamond.<module> - INFO - Starting logger.
2017-02-02 10:56:08,295 - emod.start - INFO - Starting Job Manager.
2017-02-02 10:56:08,325 - cron.run - INFO - Starting Cron Daemon.
2017-02-02 10:58:50,174 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x07207420>, trait: seconds_per_point, old value: 0.0005, new value: 5e-05
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 487.80487804878044 <type 'float'> was specified.
2017-02-02 11:02:33,387 - pi3diamond.<module> - INFO - Starting logger.
2017-02-02 11:02:35,276 - emod.start - INFO - Starting Job Manager.
2017-02-02 11:02:35,286 - cron.run - INFO - Starting Cron Daemon.
2017-02-02 11:05:28,588 - pi3diamond.<module> - INFO - Starting logger.
2017-02-02 11:05:30,588 - emod.start - INFO - Starting Job Manager.
2017-02-02 11:05:30,588 - cron.run - INFO - Starting Cron Daemon.
2017-02-02 11:51:52,318 - emod.submit - INFO - The job <measurements.confocal.Confocal object at 0x071FC690> is already running or in the queue.
2017-02-02 12:24:46,193 - pi3diamond.<module> - INFO - Starting logger.
2017-02-02 12:24:56,282 - emod.start - INFO - Starting Job Manager.
2017-02-02 12:24:56,302 - cron.run - INFO - Starting Cron Daemon.
2017-02-02 12:36:01,512 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x0720A420>, trait: resolution, old value: 50, new value: 2
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 1000.0 <type 'float'> was specified.
2017-02-02 13:58:32,168 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x0720A420>, trait: resolution, old value: 31, new value: 1
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 2000.0 <type 'float'> was specified.
2017-02-02 14:01:07,750 - auto_focus.focus - INFO - Focus: 35.68, 3.97, 2.48
2017-02-02 14:01:17,871 - auto_focus.focus - INFO - Focus: 36.08, 3.97, 2.93
2017-02-02 14:01:24,131 - auto_focus.focus - INFO - Focus: 36.08, 3.97, 2.63
2017-02-02 14:06:42,861 - auto_focus.focus - INFO - Focus: 21.91, 10.00, 3.23
2017-02-02 14:06:48,381 - auto_focus.focus - INFO - Focus: 22.01, 9.50, 3.98
2017-02-02 14:06:53,322 - auto_focus.focus - INFO - Focus: 21.71, 9.70, 4.73
2017-02-02 14:06:58,201 - auto_focus.focus - INFO - Focus: 21.41, 10.00, 4.88
2017-02-02 14:07:03,131 - auto_focus.focus - INFO - Focus: 21.61, 9.80, 5.03
2017-02-02 14:14:56,243 - auto_focus.focus - INFO - Focus: 38.58, 11.12, -5.96
2017-02-02 14:15:01,582 - auto_focus.focus - INFO - Focus: 38.58, 10.62, -6.11
2017-02-02 14:15:07,042 - auto_focus.focus - INFO - Focus: 38.48, 10.52, -5.96
2017-02-02 14:15:12,862 - auto_focus.focus - INFO - Focus: 37.98, 10.22, -5.81
2017-02-02 14:15:17,753 - auto_focus.focus - INFO - Focus: 38.08, 10.22, -5.51
2017-02-02 14:15:25,433 - auto_focus.focus - INFO - Focus: 38.08, 10.22, -5.51
2017-02-02 14:48:12,950 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x0720A420>, trait: resolution, old value: 31, new value: 1
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 2000.0 <type 'float'> was specified.
2017-02-02 14:49:44,740 - auto_focus.focus - INFO - Focus: 23.73, 35.63, -5.21
2017-02-02 14:49:49,680 - auto_focus.focus - INFO - Focus: 23.73, 35.73, -5.21
2017-02-02 14:52:06,551 - auto_focus.focus - INFO - Focus: 42.11, 10.66, -5.36
2017-02-02 14:52:11,460 - auto_focus.focus - INFO - Focus: 42.11, 10.66, -5.51
2017-02-02 14:52:18,450 - auto_focus.focus - INFO - Focus: 42.11, 10.56, -5.36
2017-02-02 14:54:36,782 - auto_focus.focus - INFO - Focus: 21.61, 4.02, -4.76
2017-02-02 14:54:41,671 - auto_focus.focus - INFO - Focus: 21.51, 3.92, -4.01
2017-02-02 14:54:46,562 - auto_focus.focus - INFO - Focus: 21.41, 3.82, -3.56
2017-02-02 14:54:51,411 - auto_focus.focus - INFO - Focus: 21.01, 3.92, -3.26
2017-02-02 14:54:56,381 - auto_focus.focus - INFO - Focus: 21.01, 3.92, -3.26
2017-02-02 14:59:09,092 - auto_focus.focus - INFO - Focus: 38.14, 7.89, -3.26
2017-02-02 14:59:16,243 - auto_focus.focus - INFO - Focus: 38.14, 7.89, -3.41
2017-02-02 15:02:11,982 - auto_focus.focus - INFO - Focus: 22.11, 4.22, -3.11
2017-02-02 15:02:18,332 - auto_focus.focus - INFO - Focus: 22.01, 4.22, -3.11
2017-02-02 15:02:24,451 - auto_focus.focus - INFO - Focus: 22.01, 4.22, -3.11
2017-02-02 15:08:06,624 - auto_focus.focus - INFO - Focus: 41.61, 12.76, -3.71
2017-02-02 15:08:11,573 - auto_focus.focus - INFO - Focus: 41.51, 12.76, -4.01
2017-02-02 15:08:16,384 - auto_focus.focus - INFO - Focus: 41.51, 12.76, -4.01
2017-02-02 15:11:42,770 - auto_focus.focus - INFO - Focus: 38.19, 12.61, -4.61
2017-02-02 15:11:55,039 - auto_focus.focus - INFO - Focus: 38.19, 12.51, -5.21
2017-02-02 15:12:02,322 - auto_focus.focus - INFO - Focus: 38.19, 12.51, -5.21
2017-02-02 15:21:27,157 - auto_focus.focus - INFO - Focus: 17.44, 12.71, -2.14
2017-02-02 15:41:18,645 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x0720A420>, trait: resolution, old value: 31, new value: 1
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 2000.0 <type 'float'> was specified.
2017-02-02 15:48:25,918 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x0720A420>, trait: resolution, old value: 31, new value: 1
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 2000.0 <type 'float'> was specified.
2017-02-02 15:48:27,309 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x0720A420>, trait: resolution, old value: 1, new value: 3
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 666.6666666666666 <type 'float'> was specified.
2017-02-02 15:56:19,012 - auto_focus.focus - INFO - Focus: 33.53, 18.19, -4.24
2017-02-02 15:56:26,371 - auto_focus.focus - INFO - Focus: 33.53, 18.09, -4.09
2017-02-02 15:56:33,752 - auto_focus.focus - INFO - Focus: 33.53, 18.09, -4.24
2017-02-02 15:59:32,931 - auto_focus.focus - INFO - Focus: 15.93, 8.49, -3.79
2017-02-02 15:59:41,092 - auto_focus.focus - INFO - Focus: 15.53, 8.69, -4.24
2017-02-02 15:59:53,302 - auto_focus.focus - INFO - Focus: 15.93, 8.19, -4.09
2017-02-02 16:08:29,427 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x0720A420>, trait: resolution, old value: 31, new value: 1
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 2000.0 <type 'float'> was specified.
2017-02-02 16:09:27,617 - auto_focus.focus - INFO - Focus: 2.57, 21.11, -4.09
2017-02-02 16:09:37,927 - auto_focus.focus - INFO - Focus: 2.47, 21.11, -4.09
2017-02-02 16:17:51,696 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x0720A420>, trait: resolution, old value: 41, new value: 3
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 666.6666666666666 <type 'float'> was specified.
2017-02-02 16:19:35,858 - auto_focus.focus - INFO - Focus: 10.96, 13.87, -4.24
2017-02-02 16:19:43,188 - auto_focus.focus - INFO - Focus: 10.96, 13.87, -4.54
2017-02-02 16:32:59,441 - auto_focus.focus - INFO - Focus: 16.50, 16.14, -4.09
2017-02-02 16:33:07,691 - auto_focus.focus - INFO - Focus: 16.50, 16.24, -3.79
2017-02-03 15:55:48,303 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x0720A420>, trait: resolution, old value: 41, new value: 1
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 2000.0 <type 'float'> was specified.
2017-02-03 16:08:53,690 - emod.submit - INFO - The job <measurements.auto_focus.AutoFocus object at 0x0B5EF090> is already running or in the queue.
2017-02-03 16:09:00,740 - auto_focus.focus - INFO - Focus: 10.54, 16.09, -0.17
2017-02-03 16:42:17,440 - auto_focus.focus - INFO - Focus: 16.19, 10.77, -0.13
2017-02-03 16:42:24,950 - auto_focus.focus - INFO - Focus: 16.39, 11.17, 0.62
2017-02-03 16:42:32,650 - auto_focus.focus - INFO - Focus: 16.79, 11.47, 1.37
2017-02-03 16:42:39,940 - auto_focus.focus - INFO - Focus: 17.19, 11.87, 2.12
2017-02-03 16:42:47,259 - auto_focus.focus - INFO - Focus: 17.59, 12.27, 2.87
2017-02-03 16:42:54,490 - auto_focus.focus - INFO - Focus: 17.79, 12.67, 3.17
2017-02-03 16:58:06,173 - auto_focus.focus - INFO - Focus: 26.84, 25.27, -9.22
2017-02-03 17:07:06,755 - auto_focus.focus - INFO - Focus: 29.90, 15.40, -8.47
2017-02-03 17:07:14,505 - auto_focus.focus - INFO - Focus: 29.70, 15.80, -7.87
2017-02-03 17:07:22,154 - auto_focus.focus - INFO - Focus: 30.00, 16.20, -8.17
2017-02-03 17:21:28,581 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x0720A420>, trait: resolution, old value: 41, new value: 1
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 2000.0 <type 'float'> was specified.
2017-02-03 17:22:30,595 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x0720A420>, trait: resolution, old value: 150, new value: 2
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 1000.0 <type 'float'> was specified.
2017-02-03 17:33:31,371 - auto_focus.focus - INFO - Focus: 24.50, 25.10, -7.42
2017-02-03 17:33:38,720 - auto_focus.focus - INFO - Focus: 24.00, 25.00, -6.67
2017-02-03 17:33:46,040 - auto_focus.focus - INFO - Focus: 23.60, 24.70, -5.92
2017-02-03 17:33:53,290 - auto_focus.focus - INFO - Focus: 23.50, 24.90, -5.47
2017-02-03 17:34:03,601 - auto_focus.focus - INFO - Focus: 23.00, 25.30, -5.62
2017-02-03 18:00:17,763 - trait_notifiers._log_exception - ERROR - Exception occurred in traits notification handler for object: <measurements.confocal.Confocal object at 0x0720A420>, trait: resolution, old value: 41, new value: 3
Traceback (most recent call last):
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 511, in rebind_call_0
    self.dispatch( getattr( self.object(), self.name ) )
  File "C:\Pythonepd\lib\site-packages\traits\trait_notifiers.py", line 628, in dispatch
    handler( *args )
  File "D:\pi3diamondnew\measurements\confocal.py", line 130, in _calculate_speed
    self.scan_speed=1.0/(self.seconds_per_point*self.resolution)
  File "C:\Pythonepd\lib\site-packages\traits\trait_handlers.py", line 170, in error
    value )
TraitError: The 'scan_speed' trait of a Confocal instance must be 0.0 <= a floating point number <= 400.0, but a value of 666.6666666666666 <type 'float'> was specified.
